### ISSUE TITLE
String IO error

### ISSUE THREAD

**Issue by bd** [nesies/urllib2_file#1]
Let me preface this by saying it is quite possible I am misusing this library. 

I tried using the test-upload script with a -f followed by (unquoted) filename. The error I got was  File "/Library/Python/2.5/site-packages/urllib2_file.py", line 102, in send_data
    if fd.**module** in ("StringIO", "cStringIO"):
AttributeError: 'file' object has no attribute '**module**'

In urllib_file.py, when I set that test to be always false (since I was not planning on using StringIO), I was able to run the script fine.

**Comment by nesies** [comment]
do you use the last version ?
there was some bugs with old ones

**Comment by bd** [comment]
I don't think so-- I downloaded it here this morning.

**Comment by nesies** [comment]
'cause in the last one, there no such line 102 with:
"if fd.**module** in ("StringIO", "cStringIO"):"

**Comment by bd** [comment]
Huh, so it is- how did I end up with the old version? Ah well, my bad. Thanks for the helpful library!
