### ISSUE TITLE
Can't upload a file when you supply a django.core.files.base.ContentFile

### ISSUE THREAD

**Issue by bradleyayers** [nesies/urllib2_file#3]
The code only checks to see if it has a 'fileno', or a 'len' attribute. You shouldn't rely on the 'len' attribute either, since it's an implementation detail. The cStringIO implementation doesn't even have the 'len' attribute.

I think the best thing you could do is, read all the data and count how much there is, then seek(0) at the end. e.g.

From line 105:

```
    if hasattr(fd, 'fileno'):
        # a File
        name = fd.name.split(os.path.sep)[-1]
        file_size = os.fstat(fd.fileno())[stat.ST_SIZE]
    elif hasattr(fd, 'len'):
        # StringIO (Note: incompatible with cStringIO)
        name = getattr(fd, 'name', k)
        file_size = fd.len
    else:
        # Final resort, read the entire message, and figure out the size.
        name = getattr(fd, 'name', k)
        file_size = 0
        while True:
            chunk = fd.read(CHUNK_SIZE)
            if chunk:
                # It's not necessarily going to be CHUNK_SIZE large, since
                # the last chunk is very likely < CHUNK_SIZE
                file_size += len(chunk)
            else:
                break
    fd.seek(0) # Ensure we start reading from the beginning.
```

**Comment by nesies** [comment]
but cStringIO does not allow you to add any attribute. I can't pass the name of the file.

I might change the API to: 
data ={
- "file":  file()
- "file": ["name", file() ]  
  }

Is cStringIO really has an advantage ?

**Comment by bradleyayers** [comment]
Sorry but I don't understand what you mean by:

```
data ={
- "file": file() + "file": ["name", file() ]
}
```

**Comment by bradleyayers** [comment]
The reason I put

```
name = getattr(fd, 'name', k)
```

in the StringIO section was in the situation that _some other_ sort of object was passed in (i.e. other than a StringIO.StringIO instance), that had both a _len_ attribute **and** a _name_ attribute, but I realise now that that approach is not ideal. There's no standard around what _len_ means, some other type of object could be passed in that has a _len_ attribute, and it could mean something completely different from _length_.

With this in mind I'd probably change the whole thing to:

```
if hasattr(fd, 'fileno'):
    # a File
    name = fd.name.split(os.path.sep)[-1]
    file_size = os.fstat(fd.fileno())[stat.ST_SIZE]
else:
    # Final resort, read the entire message, and figure out the size.
    name = getattr(fd, 'name', k)
    file_size = 0
    while True:
        chunk = fd.read(CHUNK_SIZE)
        if chunk:
            # It's not necessarily going to be CHUNK_SIZE large, since
            # the last chunk is very likely < CHUNK_SIZE
            file_size += len(chunk)
        else:
            break
fd.seek(0) # Ensure we start reading from the beginning.
```

I definitely think relying on an internal characteristic of the current implementation of StringIO.StringIO is a bad idea. having the `getattr(fd, 'name', k)` would allow Django's `django.core.files.base.ContentFile`, `django.core.files.base.File` (and any other class that follows this convention) to have it's filename recognised properly.

**Comment by nesies** [comment]
ok, i changed the data format a bit to not rely anymore on  gettattr(fd, 'name') and integrated your code
